import { requireUser } from '@/lib/auth/require-user'
import { hasPermission } from '@/lib/permissions'
import { prisma } from '@/lib/prisma'
import { FileText, Table } from 'lucide-react'
import Link from 'next/link'

export default async function ExportHistoryPage() {
  const user = await requireUser()
  if (user.role !== 'SUPER_ADMIN') {
    if (!hasPermission(user.role, 'reports.export')) throw new Error('Unauthorized')
  }

  const exportsList = await prisma.reportExport.findMany({
    where: { companyId: user.companyId! },
    orderBy: { createdAt: 'desc' },
    take: 50,
    include: {
      generatedBy: { select: { name: true } }
    }
  })

  return (
    <div className="p-4 md:p-8 max-w-7xl mx-auto space-y-6">
      <div>
        <Link href="/reports" className="text-sm text-p hover:underline mb-2 inline-block">← Back to Dashboard</Link>
        <h1 className="text-2xl font-bold">Export History</h1>
        <p className="text-sm text-mut">Recent PDF and Excel reports generated by your team.</p>
      </div>

      <div className="bg-white rounded-xl border border-line overflow-hidden shadow-sm">
        {exportsList.length === 0 ? (
          <div className="p-12 text-center text-mut">
            <p>No reports have been exported yet.</p>
          </div>
        ) : (
          <div className="overflow-x-auto">
            <table className="ct-table">
              <thead>
                <tr>
                  <th>Format</th>
                  <th>Report Type</th>
                  <th>Filters</th>
                  <th>Generated By</th>
                  <th>Date</th>
                </tr>
              </thead>
              <tbody>
                {exportsList.map(item => (
                  <tr key={item.id}>
                    <td>
                      <span className="flex items-center gap-2">
                        {item.format === 'PDF' ? <FileText className="w-4 h-4 text-red-500" /> : <Table className="w-4 h-4 text-green-500" />}
                        <span className="font-bold">{item.format}</span>
                      </span>
                    </td>
                    <td className="capitalize">{item.reportType.replace('-', ' ')}</td>
                    <td className="text-xs text-mut max-w-[200px] truncate">{JSON.stringify(item.filtersJson)}</td>
                    <td>{item.generatedBy.name}</td>
                    <td>{item.createdAt.toLocaleString('en-IN')}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </div>
    </div>
  )
}
