import { requireUser } from '@/lib/auth/require-user'
import { hasPermission } from '@/lib/permissions'
import { prisma } from '@/lib/prisma'
import { FileText, Table, ArrowLeft } from 'lucide-react'
import Link from 'next/link'

export default async function ExportHistoryPage() {
  const user = await requireUser()
  if (user.role !== 'SUPER_ADMIN') {
    if (!hasPermission(user.role, 'reports.export')) throw new Error('Unauthorized')
  }

  const exportsList = await prisma.reportExport.findMany({
    where: { companyId: user.companyId! },
    orderBy: { createdAt: 'desc' },
    take: 50,
    include: {
      generatedBy: { select: { name: true } }
    }
  })

  return (
    <div className="p-4 md:p-8 max-w-7xl mx-auto space-y-6">
      <div>
        <Link href="/reports" className="text-sm text-[#fc6e20] hover:underline mb-2 inline-flex items-center gap-1.5 font-medium">
          <ArrowLeft className="w-4 h-4" /> Back to Dashboard
        </Link>
        <h1 className="text-2xl font-bold text-gray-900">Export History</h1>
        <p className="text-sm text-gray-500">Recent PDF and Excel reports generated by your team.</p>
      </div>

      <div className="bg-white rounded-xl border border-gray-200 overflow-hidden shadow-sm">
        {exportsList.length === 0 ? (
          <div className="p-12 text-center text-gray-500 text-sm">
            <p>No reports have been exported yet.</p>
          </div>
        ) : (
          <div className="overflow-x-auto">
            <table className="w-full text-left border-collapse">
              <thead>
                <tr className="border-b border-gray-200 bg-gray-50/75">
                  <th className="px-6 py-3 text-xs font-semibold text-gray-500 uppercase tracking-wider">Format</th>
                  <th className="px-6 py-3 text-xs font-semibold text-gray-500 uppercase tracking-wider">Report Type</th>
                  <th className="px-6 py-3 text-xs font-semibold text-gray-500 uppercase tracking-wider">Filters</th>
                  <th className="px-6 py-3 text-xs font-semibold text-gray-500 uppercase tracking-wider">Generated By</th>
                  <th className="px-6 py-3 text-xs font-semibold text-gray-500 uppercase tracking-wider">Date</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-gray-100">
                {exportsList.map(item => (
                  <tr key={item.id} className="hover:bg-gray-50/50 transition-colors">
                    <td className="px-6 py-4">
                      <span className="flex items-center gap-2">
                        {item.format === 'PDF' ? <FileText className="w-4 h-4 text-rose-500" /> : <Table className="w-4 h-4 text-emerald-500" />}
                        <span className="font-semibold text-sm text-gray-900">{item.format}</span>
                      </span>
                    </td>
                    <td className="px-6 py-4 text-sm text-gray-700 capitalize font-medium">{item.reportType.replace('-', ' ')}</td>
                    <td className="px-6 py-4 text-xs text-gray-500 max-w-[200px] truncate">{JSON.stringify(item.filtersJson)}</td>
                    <td className="px-6 py-4 text-sm text-gray-700">{item.generatedBy.name}</td>
                    <td className="px-6 py-4 text-xs text-gray-500">{item.createdAt.toLocaleString('en-IN')}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </div>
    </div>
  )
}
